use_frameworks!

target 'PoporVideoTool_Example' do
  platform :ios, '9.0'
  pod 'PoporVideoTool', :path => '../'
  
  pod 'PoporUI'
  pod 'PoporFoundation'
  
  pod 'PoporMedia'
  pod 'PoporAVPlayer'
  
end

target 'PvtMac' do
  platform :macos, '10.15'
  pod 'PoporVideoTool', :path => '../'
  
end
